# Netlify Configuration for Dr.MiMi Medical Education Platform
[build]
  # Build command
  command = "npm run build"
  
  # Output directory
  publish = "dist"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "20"

# SPA Routing - Redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API Proxy - Redirect /api/* to backend server
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache Control for Assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker - No cache
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# PWA Manifest - No cache
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects for common routes
[[redirects]]
  from = "/admin"
  to = "/admin/login"
  status = 301

# Custom error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404
