blank_issues_enabled: true
contact_links:
  - name: Question ou Discussion
    url: https://github.com/ramihamdouchetraining-prog/DrMiMi-Replit/discussions
    about: Pour poser des questions ou discuter du projet
